// Case sensitive sender list (for deletion)
var senders = {
    'Hoss Tools': true,
    'Mantis France': true,
    'Mantis': true,
    'WordPress': true,
    'Famous Cookies': true,
    'Elevate Hemp': true,
    'Oakes Wholesale': true,
    'Famous 4th Street Cookies': true,
    'webadmin@ink-it.net': true,
    'Bradford White': true,
    'Oakes Daylilies': true,
    'IABCN': true,
    'Zapier': true,
    'ACXChange Support': true,
    'Stevesleaves.com': true,
    'PsPrint': true,
    'WP Engine': true,
    'Fiverr': true,
    'Vimeo': true,
    'Yelp – Philadelphia': true,
    'WooCommerce': true,
    'Trello': true,
    'Bethany from Amasty': true,
    'Stagestep': true,
    'nathaniel.forbes@locationshawaii.com': true,
    'SparkPost Team': true,
    'Dev Think IT': true,
    'Asana': true,
    'The Events Calendar': true,
    'The Events Calendar Team': true,
    'WP Engine System': true,
    'WP Engine Team': true,
    'The WP Engine Team': true,
    'Mail Delivery System': true,
    'The Content Team | Talkroute': true,
    'InstantSearch+': true,
    'PowerCorpsPHL': true,
    'WP Engine Billing (billing@billing.wpengine.com)': true,
    'OptinMonster': true,
    'WP All Import': true,
    'Steph at Asana': true,
    'Fun Times Magazine': true,
    'Tkey@hosstools.com': true,
    'Amazon Web Services': true,
    'Google': true,
    'Zapier Monthly': true,
    'bioRemediesMD': true,
    'bioRemedies MD': true,
    'Service Updates | Talkroute': true,
    'Jeffrey Shapiro': true,
    'bioREMEDIES MD': true,
    'bioREMEDIES': true,
    'Think-IT': true,
    'South Street Headhouse District': true,
    'IgniteWoo.com': true,
    'Ride Entertainment': true,
    'Elevate': true,
    'Dropbox': true,
    'Yelp': true,
    'The Veem Team': true,
    'ThinkIT Agency': true,
    'Octo Design Group': true,
    'Mantis UK': true,
    'The LogMeIn Team': true,
    'Steve\'s Leaves': true,
    'Italy-America Business Council and Network': true,
    'How To Compost': true,
    'IgniteWoo': true,
    'The Homestead Box': true,
    'Ink It Digital': true,
    'ink IT': true,
    'Mailchimp Legal': true,
    'SparkPost': true,
    'Tina Phillips': true,
    'LogMeIn Pro': true,
    'AngellEYE': true,
    'no-reply@mail.wpengine.com': true,
    'Alex R (Fiverr Customer Support)': true,
    'Gareth at WooCommerce': true,
    'Fiverr Support Team (Fiverr Customer Support)': true,
    'wordpress@bioremediesmd.com': true,
    'Jisse Reitsma': true,
    'ian.pitt@m.logmein.com': true,
    'Google Search Console Team': true,
    'LogMeIn.com Auto-Mailer': true,
    'Kuba from LiveChat': true,
    'Thomas at OptinMonster': true,
    'My Chili Store': true,
    'Modern Tribe': true,
    'Keri at OptinMonster': true,
    'Fiverr Customer Support': true,
    'Taco from Trello': true,
    'Deluxe': true,
    'Angie at OptinMonster': true,
    'Think It': true,
    'Let\'s Encrypt Expiry Bot': true,
    'BlogVault Support': true,
    'Alana at WooCommerce': true,
    'tkey hosstools.com': true,
    'New Features | Talkroute': true,
    'Mike at Zapier': true,
    'Angie at OptinMonster': true,
    'Direct CBD Online': true,
    'Patrycja from LiveChat': true,
    'Tina Phillips via Asana': true,
    'Mark Arnoldy at Asana': true,
    'Clara at WooCommerce': true,
    'Zach Tirrell': true,
    'Gumroad': true,
    'Vlad from Amasty': true,
    'WP Engine Termination': true,
    'C Murda': true,
    'Browserstack': true,
    'Chris Jones': true,
    'Vishal Kothari': true,
    'The Coronado PHX': true,
    'WPFactory': true,
    'BrowserStack': true,
    'Pantheon Customer Support': true,
    'CrashPlan for Small Business': true,
    'Nathaniel Forbes': true,
    'Zapier News': true,
    'Iconic': true,
    'Anna at Zapier': true,
    '25% off Sleep Capsules': true,
    'Ashley R via Asana': true,
    'Dustin at Asana': true

};

export default senders;